Display review data
opensafely-core/job-server pull request #2058
Opened 2022-08-25 15:36 UTC by ghickman

Add per-Release and per-ReleaseFile metadata

![](https://p198.p4.n0.cdn.getcloudapp.com/items/9ZugGdLJ/4fe00f1f-26e6-4653-ad1c-bc0e8c2df7ee.jpg?v=b46920107995653378ee366d6eed1ed9)

2022-08-25 16:51 UTC, bloodearnest requested changes

2022-08-25 16:51 UTC, bloodearnest commented on assets/src/scripts/outputs-viewer/components/Metadata/Metadata.jsx
> +          <strong>What does this file contain?</strong>
This should be the key value of the dict

2022-08-25 16:51 UTC, bloodearnest commented on assets/src/scripts/outputs-viewer/components/Metadata/Metadata.jsx
> +            How has the author ensured that this file is non-disclosive?
Same as above.

2022-08-25 16:51 UTC, bloodearnest commented on assets/src/scripts/outputs-viewer/App.jsx
> +                  context={selectedFile.metadata.context}
This should be just `metadata=metadata`

The jsx component should iterate through the key/value pairs.

To match the current document, we'd expect a dict like:

````
{
    "Context": "user input context",
    "Controls": "user input controls",
}
```

2022-08-26 07:02 UTC, ghickman commented
Updated to show what it looks like.  I'm not sold on using the keys for the labels as that ties the display to the labels of the form, but I've updated it to that so we can see what it looks like for the demo.

2022-08-26 14:13 UTC, bloodearnest commented
The keys have no semantic meaning - the can be the whole text of the form label if they want.

In fact, a dict of labels: values is a much better terminology

2022-08-29 09:55 UTC, bloodearnest approved these changes

2022-08-29 09:56 UTC, merged