Updates from opensafely-core/repo-template
opensafely-core/job-server pull request #3979
Opened 2024-01-10 20:58 UTC by iaindillingham

This adds a couple of updates from opensafely-core/repo-template. We can avoid shelling out for an environment variable, and we can better support developers who use Windows.

2024-01-11 11:56 UTC, madwort requested changes

2024-01-11 11:56 UTC, madwort commented on justfile
> +export PIP := BIN + if os_family() == "unix" { "/python -m pip" } else { "/python.exe -m pip" }
*ahem* how about `macos`?

2024-01-11 11:57 UTC, madwort commented on justfile
> +export PIP := BIN + if os_family() == "unix" { "/python -m pip" } else { "/python.exe -m pip" }
https://just.systems/man/en/chapter_31.html

2024-01-11 11:57 UTC, madwort commented on justfile
> +export PIP := BIN + if os_family() == "unix" { "/python -m pip" } else { "/python.exe -m pip" }
ignore me!

2024-01-11 12:53 UTC, iaindillingham commented
You've requested changes @madwort, but I think they're the changes you've told me that I should ignore. Is that correct?

2024-01-17 14:17 UTC, lucyb approved these changes

2024-01-17 14:17 UTC, lucyb commented on justfile
> +export VIRTUAL_ENV  := env_var_or_default("VIRTUAL_ENV", ".venv")
`env_var_or_default`

I didn't know that Just provided this. It looks very useful. Thank you!

2024-01-17 16:01 UTC, madwort approved these changes

2024-01-17 16:01 UTC, merged